version: '3.8'

services:
  alfraganus-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alfraganus_cloud_server
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config:/app/config
      - ./temp:/app/temp
    networks:
      - alfraganus_net

networks:
  alfraganus_net:
    driver: bridge
